#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 24 01:28:11 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=24
shaderPack=COBBLEVERSE - Shaders
